name: NevadaMohel
favicon: null
layout_spectrum: 0.600701856194064
typography_spectrum: 0.6294232436921448
title: "Rabbi Gadi Levy Your Newborn's Mohel for a home circumcision "
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4237800983246416
  lightness: 0.6937934854067862
  saturation: 0.08936067461036146
  rhythmicContrast: 0.2699739723466337
purpose: []
